kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "tasks"
spec:
  source:
    git:
      uri: "https://github.com/ox-prolifics/demo-pipeline.git"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: openshift-tasks/Jenkinsfile
